export type CountryType = {
  country?: string;
  capital?: string[];
  dial_code?: string;
  region?: string;
  flag?: string;
  phoneLength?: string;
};

export const countriesData: CountryType[] = [
  {
    country: "Afghanistan",
    capital: ["Kabul"],
    dial_code: "+93",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg",
  },
  {
    country: "Albania",
    capital: ["Tirana"],
    dial_code: "+355",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg",
  },
  {
    country: "Algeria",
    capital: ["Algiers"],
    dial_code: "+213",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg",
  },
  {
    country: "American Samoa",
    capital: ["Pago Pago"],
    dial_code: "+1-684",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg",
  },
  {
    country: "Andorra",
    capital: ["Andorra la Vella"],
    dial_code: "+376",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg",
  },
  {
    country: "Angola",
    capital: ["Luanda"],
    dial_code: "+244",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg",
  },
  {
    country: "Anguilla",
    capital: ["The Valley"],
    dial_code: "+1-264",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg",
  },
  {
    country: "Antarctica",
    capital: [""],
    dial_code: "",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg",
  },
  {
    country: "Antigua and Barbuda",
    capital: ["Saint John's"],
    dial_code: "+1-268",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg",
  },
  {
    country: "Argentina",
    capital: ["Buenos Aires"],
    dial_code: "+54",
    phoneLength: "6,7,8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg",
  },
  {
    country: "Armenia",
    capital: ["Yerevan"],
    dial_code: "+374",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg",
  },
  {
    country: "Aruba",
    capital: ["Oranjestad"],
    dial_code: "+297",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg",
  },
  {
    country: "Australia",
    capital: ["Canberra"],
    dial_code: "+61",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg",
  },
  {
    country: "Austria",
    capital: ["Vienna"],
    dial_code: "+43",
    phoneLength: "10,11",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg",
  },
  {
    country: "Azerbaijan",
    capital: ["Baku"],
    dial_code: "+994",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg",
  },
  {
    country: "Bahamas",
    capital: ["Nassau"],
    dial_code: "+1-242",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg",
  },
  {
    country: "Bahrain",
    capital: ["Manama"],
    dial_code: "+973",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg",
  },
  {
    country: "Bangladesh",
    capital: ["Dhaka"],
    dial_code: "+880",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg",
  },
  {
    country: "Barbados",
    capital: ["Bridgetown"],
    dial_code: "+1-246",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg",
  },
  {
    country: "Belarus",
    capital: ["Minsk"],
    dial_code: "+375",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg",
  },
  {
    country: "Belgium",
    capital: ["Brussels"],
    dial_code: "+32",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg",
  },
  {
    country: "Belize",
    capital: ["Belmopan"],
    dial_code: "+501",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg",
  },
  {
    country: "Benin",
    capital: ["Porto-Novo"],
    dial_code: "+229",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg",
  },
  {
    country: "Bermuda",
    capital: ["Hamilton"],
    dial_code: "+1-441",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg",
  },
  {
    country: "Bhutan",
    capital: ["Thimphu"],
    dial_code: "+975",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg",
  },
  {
    country: "Bolivia, Plurinational State of",
    capital: ["Sucre"],
    dial_code: "+591",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg",
  },
  {
    country: "Bosnia and Herzegovina",
    capital: ["Sarajevo"],
    dial_code: "+387",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg",
  },
  {
    country: "Botswana",
    capital: ["Gaborone"],
    dial_code: "+267",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg",
  },
  {
    country: "Brazil",
    capital: ["Brasília"],
    dial_code: "+55",
    phoneLength: "11",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
  },
  {
    country: "British Indian Ocean Territory",
    capital: ["Diego Garcia"],
    dial_code: "+246",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IO.svg",
  },
  {
    country: "Brunei Darussalam",
    capital: ["Bandar Seri Begawan"],
    dial_code: "+673",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg",
  },
  {
    country: "Bulgaria",
    capital: ["Sofia"],
    dial_code: "+359",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg",
  },
  {
    country: "Burkina Faso",
    capital: ["Ouagadougou"],
    dial_code: "+226",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg",
  },
  {
    country: "Burundi",
    capital: ["Gitega"],
    dial_code: "+257",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg",
  },
  {
    country: "Cambodia",
    capital: ["Phnom Penh"],
    dial_code: "+855",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg",
  },
  {
    country: "Cameroon",
    capital: ["Yaoundé"],
    dial_code: "+237",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg",
  },
  {
    country: "Canada",
    capital: ["Ottawa"],
    dial_code: "+1",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg",
  },
  {
    country: "Cape Verde",
    capital: ["Praia"],
    dial_code: "+238",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg",
  },
  {
    country: "Cayman Islands",
    capital: ["George Town"],
    dial_code: "+1-345",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KY.svg",
  },
  {
    country: "Central African Republic",
    capital: ["Bangui"],
    dial_code: "+236",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg",
  },
  {
    country: "Chad",
    capital: ["N'Djamena"],
    dial_code: "+235",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg",
  },
  {
    country: "Chile",
    capital: ["Santiago"],
    dial_code: "+56",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg",
  },
  {
    country: "China",
    capital: ["Beijing"],
    dial_code: "+86",
    phoneLength: "11",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg",
  },
  {
    country: "Christmas Island",
    capital: ["Flying Fish Cove"],
    dial_code: "+61",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg",
  },
  {
    country: "Cocos (Keeling) Islands",
    capital: ["West Island"],
    dial_code: "+61",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg",
  },
  {
    country: "Colombia",
    capital: ["Bogotá"],
    dial_code: "+57",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg",
  },
  {
    country: "Comoros",
    capital: ["Moroni"],
    dial_code: "+269",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg",
  },
  {
    country: "Congo",
    capital: ["Brazzaville"],
    dial_code: "+242",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg",
  },
  {
    country: "Congo, the Democratic Republic of the",
    capital: ["Kinshasa"],
    dial_code: "+243",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg",
  },
  {
    country: "Cook Islands",
    capital: ["Avarua"],
    dial_code: "+682",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg",
  },
  {
    country: "Costa Rica",
    capital: ["San José"],
    dial_code: "+506",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg",
  },
  {
    country: "Croatia",
    capital: ["Zagreb"],
    dial_code: "+385",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg",
  },
  {
    country: "Cuba",
    capital: ["Havana"],
    dial_code: "+53",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg",
  },
  {
    country: "Curaçao",
    capital: ["Willemstad"],
    dial_code: "+599",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg",
  },
  {
    country: "Cyprus",
    capital: ["Nicosia"],
    dial_code: "+357",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg",
  },
  {
    country: "Czech Republic",
    capital: ["Prague"],
    dial_code: "+420",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg",
  },
  {
    country: "Côte d'Ivoire",
    capital: ["Yamoussoukro"],
    dial_code: "+225",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg",
  },
  {
    country: "Denmark",
    capital: ["Copenhagen"],
    dial_code: "+45",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg",
  },
  {
    country: "Djibouti",
    capital: ["Djibouti"],
    dial_code: "+253",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg",
  },
  {
    country: "Dominica",
    capital: ["Roseau"],
    dial_code: "+1-767",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg",
  },
  {
    country: "Dominican Republic",
    capital: ["Santo Domingo"],
    dial_code: "+1-809",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg",
  },
  {
    country: "Dominican Republic",
    capital: ["Santo Domingo"],
    dial_code: "+1-829",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg",
  },
  {
    country: "Ecuador",
    capital: ["Quito"],
    dial_code: "+593",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg",
  },
  {
    country: "Egypt",
    capital: ["Cairo"],
    dial_code: "+20",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg",
  },
  {
    country: "El Salvador",
    capital: ["San Salvador"],
    dial_code: "+503",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg",
  },
  {
    country: "Equatorial Guinea",
    capital: ["Malabo"],
    dial_code: "+240",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg",
  },
  {
    country: "Eritrea",
    capital: ["Asmara"],
    dial_code: "+291",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg",
  },
  {
    country: "Estonia",
    capital: ["Tallinn"],
    dial_code: "+372",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg",
  },
  {
    country: "Ethiopia",
    capital: ["Addis Ababa"],
    dial_code: "+251",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg",
  },
  {
    country: "Falkland Islands (Malvinas)",
    capital: ["Stanley"],
    dial_code: "+500",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg",
  },
  {
    country: "Faroe Islands",
    capital: ["Tórshavn"],
    dial_code: "+298",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg",
  },
  {
    country: "Fiji",
    capital: ["Suva"],
    dial_code: "+679",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg",
  },
  {
    country: "Finland",
    capital: ["Helsinki"],
    dial_code: "+358",
    phoneLength: "",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg",
  },
  {
    country: "France",
    capital: ["Paris"],
    dial_code: "+33",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg",
  },
  {
    country: "French Guiana",
    capital: ["Cayenne"],
    dial_code: "+594",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg",
  },
  {
    country: "French Polynesia",
    capital: ["Papeetē"],
    dial_code: "+689",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg",
  },
  {
    country: "French Southern Territories",
    capital: ["Port-aux-Français"],
    dial_code: "+",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TF.svg",
  },
  {
    country: "Gabon",
    capital: ["Libreville"],
    dial_code: "+241",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg",
  },
  {
    country: "Gambia",
    capital: ["Banjul"],
    dial_code: "+220",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg",
  },
  {
    country: "Georgia",
    capital: ["Tbilisi"],
    dial_code: "+995",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg",
  },
  {
    country: "Germany",
    capital: ["Berlin"],
    dial_code: "+49",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg",
  },
  {
    country: "Ghana",
    capital: ["Accra"],
    dial_code: "+233",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg",
  },
  {
    country: "Gibraltar",
    capital: ["Gibraltar"],
    dial_code: "+350",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg",
  },
  {
    country: "Greece",
    capital: ["Athens"],
    dial_code: "+30",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg",
  },
  {
    country: "Greenland",
    capital: ["Nuuk"],
    dial_code: "+299",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg",
  },
  {
    country: "Grenada",
    capital: ["St. George's"],
    dial_code: "+1-473",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg",
  },
  {
    country: "Guadeloupe",
    capital: ["Basse-Terre"],
    dial_code: "+590",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GP.svg",
  },
  {
    country: "Guam",
    capital: ["Hagåtña"],
    dial_code: "+1-671",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg",
  },
  {
    country: "Guatemala",
    capital: ["Guatemala City"],
    dial_code: "+502",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg",
  },
  {
    country: "Guernsey",
    capital: ["St. Peter Port"],
    dial_code: "+44-1481",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GG.svg",
  },
  {
    country: "Guinea",
    capital: ["Conakry"],
    dial_code: "+224",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg",
  },
  {
    country: "Guinea-Bissau",
    capital: ["Bissau"],
    dial_code: "+245",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg",
  },
  {
    country: "Guyana",
    capital: ["Georgetown"],
    dial_code: "+592",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg",
  },
  {
    country: "Haiti",
    capital: ["Port-au-Prince"],
    dial_code: "+509",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg",
  },
  {
    country: "Holy See (Vatican City State)",
    capital: ["Vatican City"],
    dial_code: "+379",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg",
  },
  {
    country: "Honduras",
    capital: ["Tegucigalpa"],
    dial_code: "+504",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg",
  },
  {
    country: "Hong Kong",
    capital: ["City of Victoria"],
    dial_code: "+852",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg",
  },
  {
    country: "Hungary",
    capital: ["Budapest"],
    dial_code: "+36",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg",
  },
  {
    country: "Iceland",
    capital: ["Reykjavik"],
    dial_code: "+354",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg",
  },
  {
    country: "India",
    capital: ["New Delhi"],
    dial_code: "+91",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg",
  },
  {
    country: "Indonesia",
    capital: ["Jakarta"],
    dial_code: "+62",
    phoneLength: "11",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg",
  },
  {
    country: "Iran, Islamic Republic of",
    capital: ["Tehran"],
    dial_code: "+98",
    phoneLength: "11",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg",
  },
  {
    country: "Iraq",
    capital: ["Baghdad"],
    dial_code: "+964",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg",
  },
  {
    country: "Ireland",
    capital: ["Dublin"],
    dial_code: "+353",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg",
  },
  {
    country: "Isle of Man",
    capital: ["Douglas"],
    dial_code: "+44-1624",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg",
  },
  {
    country: "Israel",
    capital: ["Jerusalem"],
    dial_code: "+972",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg",
  },
  {
    country: "Italy",
    capital: ["Rome"],
    dial_code: "+39",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg",
  },
  {
    country: "Jamaica",
    capital: ["Kingston"],
    dial_code: "+1-876",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg",
  },
  {
    country: "Japan",
    capital: ["Tokyo"],
    dial_code: "+81",
    phoneLength: "",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg",
  },
  {
    country: "Jersey",
    capital: ["Saint Helier"],
    dial_code: "+44-1534",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg",
  },
  {
    country: "Jordan",
    capital: ["Amman"],
    dial_code: "+962",
    phoneLength: "8,9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg",
  },
  {
    country: "Kazakhstan",
    capital: ["Nur-Sultan"],
    dial_code: "+7",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg",
  },
  {
    country: "Kenya",
    capital: ["Nairobi"],
    dial_code: "+254",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg",
  },
  {
    country: "Kiribati",
    capital: ["South Tarawa"],
    dial_code: "+686",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg",
  },
  {
    country: "Korea, Democratic People's Republic of",
    capital: ["Pyongyang"],
    dial_code: "+850",
    phoneLength: "4,6,7,13",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg",
  },
  {
    country: "Korea, Republic of",
    capital: ["Seoul"],
    dial_code: "+82",
    phoneLength: "7,8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg",
  },
  {
    country: "Kuwait",
    capital: ["Kuwait City"],
    dial_code: "+965",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg",
  },
  {
    country: "Kyrgyzstan",
    capital: ["Bishkek"],
    dial_code: "+996",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg",
  },
  {
    country: "Lao People's Democratic Republic",
    capital: ["Vientiane"],
    dial_code: "+856",
    phoneLength: "8,9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg",
  },
  {
    country: "Latvia",
    capital: ["Riga"],
    dial_code: "+371",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg",
  },
  {
    country: "Lebanon",
    capital: ["Beirut"],
    dial_code: "+961",
    phoneLength: "7,8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg",
  },
  {
    country: "Lesotho",
    capital: ["Maseru"],
    dial_code: "+266",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg",
  },
  {
    country: "Liberia",
    capital: ["Monrovia"],
    dial_code: "+231",
    phoneLength: "8,9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg",
  },
  {
    country: "Libya",
    capital: ["Tripoli"],
    dial_code: "+218",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg",
  },
  {
    country: "Liechtenstein",
    capital: ["Vaduz"],
    dial_code: "+423",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg",
  },
  {
    country: "Lithuania",
    capital: ["Vilnius"],
    dial_code: "+370",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg",
  },
  {
    country: "Luxembourg",
    capital: ["Luxembourg"],
    dial_code: "+352",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg",
  },
  {
    country: "Macao",
    capital: ["Macao"],
    dial_code: "+853",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg",
  },
  {
    country: "Macedonia, the Former Yugoslav Republic of",
    capital: ["Skopje"],
    dial_code: "+389",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg",
  },
  {
    country: "Madagascar",
    capital: ["Antananarivo"],
    dial_code: "+261",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg",
  },
  {
    country: "Malawi",
    capital: ["Lilongwe"],
    dial_code: "+265",
    phoneLength: "7,8,9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg",
  },
  {
    country: "Malaysia",
    capital: ["Kuala Lumpur"],
    dial_code: "+60",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg",
  },
  {
    country: "Maldives",
    capital: ["Malé"],
    dial_code: "+960",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg",
  },
  {
    country: "Mali",
    capital: ["Bamako"],
    dial_code: "+223",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg",
  },
  {
    country: "Malta",
    capital: ["Valletta"],
    dial_code: "+356",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg",
  },
  {
    country: "Marshall Islands",
    capital: ["Majuro"],
    dial_code: "+692",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg",
  },
  {
    country: "Martinique",
    capital: ["Fort-de-France"],
    dial_code: "+596",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg",
  },
  {
    country: "Mauritania",
    capital: ["Nouakchott"],
    dial_code: "+222",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg",
  },
  {
    country: "Mauritius",
    capital: ["Port Louis"],
    dial_code: "+230",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg",
  },
  {
    country: "Mayotte",
    capital: ["Mamoudzou"],
    dial_code: "+262",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg",
  },
  {
    country: "Mexico",
    capital: ["Mexico City"],
    dial_code: "+52",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg",
  },
  {
    country: "Micronesia, Federated States of",
    capital: ["Palikir"],
    dial_code: "+691",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg",
  },
  {
    country: "Moldova, Republic of",
    capital: ["Chișinău"],
    dial_code: "+373",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg",
  },
  {
    country: "Monaco",
    capital: ["Monaco"],
    dial_code: "+377",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg",
  },
  {
    country: "Mongolia",
    capital: ["Ulan Bator"],
    dial_code: "+976",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg",
  },
  {
    country: "Montenegro",
    capital: ["Podgorica"],
    dial_code: "+382",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg",
  },
  {
    country: "Montserrat",
    capital: ["Plymouth"],
    dial_code: "+1-664",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg",
  },
  {
    country: "Morocco",
    capital: ["Rabat"],
    dial_code: "+212",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg",
  },
  {
    country: "Mozambique",
    capital: ["Maputo"],
    dial_code: "+258",
    phoneLength: "12",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg",
  },
  {
    country: "Myanmar",
    capital: ["Naypyidaw"],
    dial_code: "+95",
    phoneLength: "",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg",
  },
  {
    country: "Namibia",
    capital: ["Windhoek"],
    dial_code: "+264",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg",
  },
  {
    country: "Nauru",
    capital: ["Yaren"],
    dial_code: "+674",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg",
  },
  {
    country: "Nepal",
    capital: ["Kathmandu"],
    dial_code: "+977",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg",
  },
  {
    country: "Netherlands",
    capital: ["Amsterdam"],
    dial_code: "+31",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg",
  },
  {
    country: "New Caledonia",
    capital: ["Nouméa"],
    dial_code: "+687",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg",
  },
  {
    country: "New Zealand",
    capital: ["Wellington"],
    dial_code: "+64",
    phoneLength: "8,9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg",
  },
  {
    country: "Nicaragua",
    capital: ["Managua"],
    dial_code: "+505",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg",
  },
  {
    country: "Niger",
    capital: ["Niamey"],
    dial_code: "+227",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg",
  },
  {
    country: "Nigeria",
    capital: ["Abuja"],
    dial_code: "+234",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg",
  },
  {
    country: "Niue",
    capital: ["Alofi"],
    dial_code: "+683",
    phoneLength: "4",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg",
  },
  {
    country: "Norfolk Island",
    capital: ["Kingston"],
    dial_code: "+672",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg",
  },
  {
    country: "Northern Mariana Islands",
    capital: ["Saipan"],
    dial_code: "+1-670",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg",
  },
  {
    country: "Norway",
    capital: ["Oslo"],
    dial_code: "+47",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg",
  },
  {
    country: "Oman",
    capital: ["Muscat"],
    dial_code: "+968",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg",
  },
  {
    country: "Pakistan",
    capital: ["Islamabad"],
    dial_code: "+92",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg",
  },
  {
    country: "Palau",
    capital: ["Ngerulmud"],
    dial_code: "+680",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg",
  },
  {
    country: "Palestine, State of",
    capital: ["Ramallah", "Jerusalem"],
    dial_code: "+970",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg",
  },
  {
    country: "Panama",
    capital: ["Panama City"],
    dial_code: "+507",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg",
  },
  {
    country: "Papua New Guinea",
    capital: ["Port Moresby"],
    dial_code: "+675",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg",
  },
  {
    country: "Paraguay",
    capital: ["Asunción"],
    dial_code: "+595",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg",
  },
  {
    country: "Peru",
    capital: ["Lima"],
    dial_code: "+51",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg",
  },
  {
    country: "Philippines",
    capital: ["Manila"],
    dial_code: "+63",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg",
  },
  {
    country: "Pitcairn",
    capital: ["Adamstown"],
    dial_code: "+870",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg",
  },
  {
    country: "Poland",
    capital: ["Warsaw"],
    dial_code: "+48",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg",
  },
  {
    country: "Portugal",
    capital: ["Lisbon"],
    dial_code: "+351",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg",
  },
  {
    country: "Puerto Rico",
    capital: ["San Juan"],
    dial_code: "+1-787",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg",
  },
  {
    country: "Puerto Rico",
    capital: ["San Juan"],
    dial_code: "+1-939",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg",
  },
  {
    country: "Qatar",
    capital: ["Doha"],
    dial_code: "+974",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg",
  },
  {
    country: "Romania",
    capital: ["Bucharest"],
    dial_code: "+40",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg",
  },
  {
    country: "Russian Federation",
    capital: ["Moscow"],
    dial_code: "+7",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg",
  },
  {
    country: "Rwanda",
    capital: ["Kigali"],
    dial_code: "+250",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg",
  },
  {
    country: "Réunion",
    capital: ["Saint-Denis"],
    dial_code: "+262",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg",
  },
  {
    country: "Saint Barthélemy",
    capital: ["Gustavia"],
    dial_code: "+590",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg",
  },
  {
    country: "Saint Helena, Ascension and Tristan da Cunha",
    capital: ["Jamestown"],
    dial_code: "+290",
    phoneLength: "4",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg",
  },
  {
    country: "Saint Kitts and Nevis",
    capital: ["Basseterre"],
    dial_code: "+1-869",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg",
  },
  {
    country: "Saint Lucia",
    capital: ["Castries"],
    dial_code: "+1-758",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg",
  },
  {
    country: "Saint Martin (French part)",
    capital: ["Marigot"],
    dial_code: "+590",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MF.svg",
  },
  {
    country: "Saint Pierre and Miquelon",
    capital: ["Saint-Pierre"],
    dial_code: "+508",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg",
  },
  {
    country: "Saint Vincent and the Grenadines",
    capital: ["Kingstown"],
    dial_code: "+1-784",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg",
  },
  {
    country: "Samoa",
    capital: ["Apia"],
    dial_code: "+685",
    phoneLength: "5,6,7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg",
  },
  {
    country: "San Marino",
    capital: ["City of San Marino"],
    dial_code: "+378",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg",
  },
  {
    country: "Sao Tome and Principe",
    capital: ["São Tomé"],
    dial_code: "+239",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg",
  },
  {
    country: "Saudi Arabia",
    capital: ["Riyadh"],
    dial_code: "+966",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg",
  },
  {
    country: "Senegal",
    capital: ["Dakar"],
    dial_code: "+221",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg",
  },
  {
    country: "Serbia",
    capital: ["Belgrade"],
    dial_code: "+381",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg",
  },
  {
    country: "Seychelles",
    capital: ["Victoria"],
    dial_code: "+248",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg",
  },
  {
    country: "Sierra Leone",
    capital: ["Freetown"],
    dial_code: "+232",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg",
  },
  {
    country: "Singapore",
    capital: ["Singapore"],
    dial_code: "+65",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg",
  },
  {
    country: "Sint Maarten (Dutch part)",
    capital: ["Philipsburg"],
    dial_code: "+599",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg",
  },
  {
    country: "Slovakia",
    capital: ["Bratislava"],
    dial_code: "+421",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg",
  },
  {
    country: "Slovenia",
    capital: ["Ljubljana"],
    dial_code: "+386",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg",
  },
  {
    country: "Solomon Islands",
    capital: ["Honiara"],
    dial_code: "+677",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg",
  },
  {
    country: "Somalia",
    capital: ["Mogadishu"],
    dial_code: "+252",
    phoneLength: "8,9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg",
  },
  {
    country: "South Africa",
    capital: ["Pretoria", "Bloemfontein", "Cape Town"],
    dial_code: "+27",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg",
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    capital: ["King Edward Point"],
    dial_code: "+",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GS.svg",
  },
  {
    country: "South Sudan",
    capital: ["Juba"],
    dial_code: "+211",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg",
  },
  {
    country: "Spain",
    capital: ["Madrid"],
    dial_code: "+34",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg",
  },
  {
    country: "Sri Lanka",
    capital: ["Sri Jayawardenepura Kotte"],
    dial_code: "+94",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg",
  },
  {
    country: "Sudan",
    capital: ["Khartoum"],
    dial_code: "+249",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg",
  },
  {
    country: "Suriname",
    capital: ["Paramaribo"],
    dial_code: "+597",
    phoneLength: "6,7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg",
  },
  {
    country: "Svalbard and Jan Mayen",
    capital: ["Longyearbyen"],
    dial_code: "+47",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg",
  },
  {
    country: "Swaziland",
    capital: ["Mbabane"],
    dial_code: "+268",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg",
  },
  {
    country: "Sweden",
    capital: ["Stockholm"],
    dial_code: "+46",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg",
  },
  {
    country: "Switzerland",
    capital: ["Bern"],
    dial_code: "+41",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg",
  },
  {
    country: "Syrian Arab Republic",
    capital: ["Damascus"],
    dial_code: "+963",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg",
  },
  {
    country: "Taiwan, Province of China",
    capital: ["Taipei"],
    dial_code: "+886",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg",
  },
  {
    country: "Tajikistan",
    capital: ["Dushanbe"],
    dial_code: "+992",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg",
  },
  {
    country: "Tanzania, United Republic of",
    capital: ["Dodoma"],
    dial_code: "+255",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg",
  },
  {
    country: "Thailand",
    capital: ["Bangkok"],
    dial_code: "+66",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg",
  },
  {
    country: "Timor-Leste",
    capital: ["Dili"],
    dial_code: "+670",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg",
  },
  {
    country: "Togo",
    capital: ["Lomé"],
    dial_code: "+228",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg",
  },
  {
    country: "Tokelau",
    capital: ["Fakaofo"],
    dial_code: "+690",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TK.svg",
  },
  {
    country: "Tonga",
    capital: ["Nuku'alofa"],
    dial_code: "+676",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg",
  },
  {
    country: "Trinidad and Tobago",
    capital: ["Port of Spain"],
    dial_code: "+1-868",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg",
  },
  {
    country: "Tunisia",
    capital: ["Tunis"],
    dial_code: "+216",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg",
  },
  {
    country: "Turkey",
    capital: ["Ankara"],
    dial_code: "+90",
    phoneLength: "11",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg",
  },
  {
    country: "Turkmenistan",
    capital: ["Ashgabat"],
    dial_code: "+993",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg",
  },
  {
    country: "Turks and Caicos Islands",
    capital: ["Cockburn Town"],
    dial_code: "+1-649",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg",
  },
  {
    country: "Tuvalu",
    capital: ["Funafuti"],
    dial_code: "+688",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg",
  },
  {
    country: "Uganda",
    capital: ["Kampala"],
    dial_code: "+256",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg",
  },
  {
    country: "Ukraine",
    capital: ["Kyiv"],
    dial_code: "+380",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg",
  },
  {
    country: "United Arab Emirates",
    capital: ["Abu Dhabi"],
    dial_code: "+971",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg",
  },
  {
    country: "United Kingdom",
    capital: ["London"],
    dial_code: "+44",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg",
  },
  {
    country: "United States",
    capital: ["Washington, D.C."],
    dial_code: "+1",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg",
  },
  {
    country: "Uruguay",
    capital: ["Montevideo"],
    dial_code: "+598",
    phoneLength: "8",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg",
  },
  {
    country: "Uzbekistan",
    capital: ["Tashkent"],
    dial_code: "+998",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg",
  },
  {
    country: "Vanuatu",
    capital: ["Port Vila"],
    dial_code: "+678",
    phoneLength: "5",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg",
  },
  {
    country: "Venezuela, Bolivarian Republic of",
    capital: ["Caracas"],
    dial_code: "+58",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg",
  },
  {
    country: "Viet Nam",
    capital: ["Hanoi"],
    dial_code: "+84",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg",
  },
  {
    country: "Virgin Islands, British",
    capital: ["Road Town"],
    dial_code: "+1-284",
    phoneLength: "7",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg",
  },
  {
    country: "Virgin Islands, U.S.",
    capital: ["Charlotte Amalie"],
    dial_code: "+1-340",
    phoneLength: "10",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg",
  },
  {
    country: "Wallis and Futuna",
    capital: ["Mata-Utu"],
    dial_code: "+681",
    phoneLength: "6",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg",
  },
  {
    country: "Yemen",
    capital: ["Sana'a"],
    dial_code: "+967",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg",
  },
  {
    country: "Zambia",
    capital: ["Lusaka"],
    dial_code: "+260",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg",
  },
  {
    country: "Zimbabwe",
    capital: ["Harare"],
    dial_code: "+263",
    phoneLength: "9",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg",
  },
  {
    country: "Åland Islands",
    capital: ["Mariehamn"],
    dial_code: "+358-18",
    phoneLength: "",
    flag: "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg",
  },
];
